// Theme constants extracted from code.html tailwind config
// Used for inline styles where NativeWind classes don't suffice

export const COLORS = {
    "on-surface-variant": "#454933",
    "on-tertiary-container": "#5e5f60",
    "secondary-container": "#e0e4dc",
    "surface-container": "#efeded",
    "primary-fixed-dim": "#b2d400",
    "on-primary-container": "#556600",
    "inverse-surface": "#111111",
    "on-surface": "#1b1c1c",
    "inverse-on-surface": "#f2f0f0",
    "secondary-fixed-dim": "#c4c8c1",
    "primary-fixed": "#c4e900",
    "surface-variant": "#e4e2e2",
    "on-tertiary": "#ffffff",
    "primary-container": "#c4e900",
    "on-secondary-fixed-variant": "#444843",
    "on-error-container": "#93000a",
    "error": "#ba1a1a",
    "surface": "#fbf9f8",
    "on-primary": "#ffffff",
    "secondary": "#5b5f5a",
    "on-error": "#ffffff",
    "on-secondary-container": "#616560",
    "on-tertiary-fixed-variant": "#454747",
    "secondary-fixed": "#e0e4dc",
    "on-secondary-fixed": "#191d18",
    "surface-container-highest": "#e4e2e2",
    "surface-bright": "#fbf9f8",
    "tertiary-fixed": "#e2e2e2",
    "tertiary-container": "#dadada",
    "inverse-primary": "#b2d400",
    "surface-tint": "#546500",
    "surface-container-lowest": "#ffffff",
    "outline-variant": "#c5c9ad",
    "on-background": "#1b1c1c",
    "on-primary-fixed": "#181e00",
    "surface-container-low": "#f5f3f3",
    "surface-container-high": "#e9e8e7",
    "tertiary-fixed-dim": "#c6c6c6",
    "on-tertiary-fixed": "#1a1c1c",
    "background": "#fbf9f8",
    "on-primary-fixed-variant": "#3f4c00",
    "surface-dim": "#dbdad9",
    "outline": "#757961",
    "primary": "#546500",
    "error-container": "#ffdad6",
    "on-secondary": "#ffffff",
    "tertiary": "#5d5f5f",
};

export const ROLES = [
    {
        id: "customer",
        title: "Customer",
        desc: "Search, book, and manage vehicle rentals",
        badge: "Most Common",
        iconName: "FaHome",
        borderColor: "#1b1c1c",
        bgSelected: "#F8FBE8",
    },
    {
        id: "vendor",
        title: "Vendor / Fleet Owner",
        desc: "List vehicles, manage bookings and earnings",
        badge: "Business",
        iconName: "FaUser",
        borderColor: "#2563eb",
        bgSelected: "#eff6ff",
    },
    {
        id: "driver",
        title: "Driver",
        desc: "Accept trips, navigate, track earnings",
        badge: "Field",
        iconName: "FaBell",
        borderColor: "#ea580c",
        bgSelected: "#fff7ed",
    },
    {
        id: "admin",
        title: "Administrator",
        desc: "Manage the entire platform, approvals, analytics",
        badge: "Internal",
        iconName: "FaCog",
        borderColor: "#7c3aed",
        bgSelected: "#f5f3ff",
    },
];

export const COMPLETED_TRIPS = [
    { name: "Arjun Mehta", route: "Koramangala → Whitefield · 18.2 km", price: "₹820", time: "2h ago" },
    { name: "Rohit Gupta", route: "Indiranagar → Electronic City · 22.1 km", price: "₹980", time: "5h ago" },
    { name: "Sneha J.", route: "Jayanagar → Hebbal · 14.5 km", price: "₹640", time: "8h ago" },
];
