name: Security Scan

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Frontend Dependencies
        working-directory: ./SmartRide-Frontend
        run: npm install

      - name: Frontend Security Audit
        working-directory: ./SmartRide-Frontend
        run: npm audit --audit-level=high